services:
  - type: web
    name: cefet-main
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn projeto.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --access-logfile - --error-logfile -"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DEBUG
        value: "False"
      - key: GROQ_API_KEY
        sync: false
      - key: GA_MEASUREMENT_ID
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
